services:
  mariadb:
    image: bitnami/mariadb
    container_name: mariadb
    environment:
      ALLOW_EMPTY_PASSWORD: yes
      MARIADB_ROOT_PASSWORD: blas1234
      MARIADB_USER: blas1234
      MARIADB_DATABASE: laravel
    ports:
      - "3305:3306"
    volumes:
      - mariadb_chat_real_time:/bitnami/mariadb
    networks:
      - red_laravel

  laravel:
    image: bitnami/laravel
    container_name: laravel
    working_dir: /var/www/html
    environment:
      DB_HOST: mariadb
      DB_PORT: 3306
      DB_USERNAME: blas1234
      DB_DATABASE: laravel
    depends_on:
      - mariadb
    networks:
      - red_laravel
    ports:
      - "8000:8000"
    volumes:
      -  ./chat_real_time:/var/www/html
    command: sh -c "chmod -R 777 vendor/ && php artisan serve --host=0.0.0.0 --port=8000"

networks:
  red_laravel:
    driver: bridge

volumes:
  mariadb_chat_real_time: